name: flutter_skeleton
description: Flutter Skeleton

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  provider: ^6.0.2
  easy_localization: ^3.0.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter_form_builder: ^7.1.0
  form_builder_validators: ^7.4.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/

